#!/usr/bin/env python3
"""Geometry-independent algebra of curve reversal and mirror relations.

This module is the formal specialization layer between generic word solving and
numeric polygonal templates.  It reads only terminal segment correspondences,
orientation signs and copy parity.  Its four transformations form the Klein
group generated by path inversion and mirror conjugation.

No coordinates, polyline vertices, lengths, kappas or optimizer parameters are
used here.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple


SCHEMA_VERSION = "curve-relation-algebra-v1"


class CurveRelationError(ValueError):
    pass


@dataclass(frozen=True, order=True)
class CurveTransform:
    reverse: bool = False
    mirror: bool = False

    def compose(self, other: "CurveTransform") -> "CurveTransform":
        return CurveTransform(
            reverse=self.reverse ^ other.reverse,
            mirror=self.mirror ^ other.mirror,
        )

    @property
    def label(self) -> str:
        if self.reverse and self.mirror:
            return "mirror_reverse"
        if self.reverse:
            return "reverse"
        if self.mirror:
            return "mirror"
        return "identity"


IDENTITY = CurveTransform()
REVERSE = CurveTransform(reverse=True)
MIRROR = CurveTransform(mirror=True)
MIRROR_REVERSE = CurveTransform(reverse=True, mirror=True)


@dataclass(frozen=True)
class CurveRelation:
    left_variable: str
    right_variable: str
    transform: CurveTransform
    copy_index: int
    pair_index: int
    source_position: int
    target_position: int

    def to_dict(self) -> Dict[str, object]:
        return {
            "left_variable": self.left_variable,
            "right_variable": self.right_variable,
            "transform": self.transform.label,
            "copy_index": self.copy_index,
            "pair_index": self.pair_index,
            "source_position": self.source_position,
            "target_position": self.target_position,
        }


@dataclass(frozen=True)
class CurveRelationComponent:
    index: int
    representative: str
    variables: Tuple[str, ...]
    transforms: Mapping[str, CurveTransform]
    symmetry_group: Tuple[CurveTransform, ...]
    mode: str

    def to_dict(self) -> Dict[str, object]:
        return {
            "component_index": self.index,
            "representative": self.representative,
            "variables": list(self.variables),
            "variable_transforms": {
                variable: self.transforms[variable].label
                for variable in self.variables
            },
            "self_symmetry_group": [item.label for item in self.symmetry_group],
            "formal_mode": self.mode,
        }


@dataclass(frozen=True)
class CurveRelationAnalysis:
    enabled: bool
    components: Tuple[CurveRelationComponent, ...]
    component_by_variable: Mapping[str, int]
    relations: Tuple[CurveRelation, ...]

    def component_for(self, variable: str) -> CurveRelationComponent:
        return self.components[self.component_by_variable[variable]]

    def to_dict(self) -> Dict[str, object]:
        return {
            "schema_version": SCHEMA_VERSION,
            "enabled": self.enabled,
            "component_count": len(self.components),
            "relation_count": len(self.relations),
            "components": [component.to_dict() for component in self.components],
            "relations": [relation.to_dict() for relation in self.relations],
        }


@dataclass(frozen=True)
class _Occurrence:
    variable: str
    inverse: bool


def _effective_orientation(occurrence: _Occurrence, directed_orientation: int) -> int:
    if directed_orientation not in (-1, 1):
        raise CurveRelationError(
            f"Directed segment orientation must be +/-1, got {directed_orientation!r}"
        )
    return (-1 if occurrence.inverse else 1) * directed_orientation


def _parse_relations(
    occurrences: Sequence[_Occurrence],
    terminal_mapping: Mapping[str, object],
) -> Tuple[CurveRelation, ...]:
    if not isinstance(terminal_mapping, Mapping):
        raise CurveRelationError(
            "Missing terminal_mapping. Rerun the formal audit before interpreting "
            "Straight/Mirror curve terms."
        )
    segment_count = int(terminal_mapping.get("segment_count", -1))
    if segment_count != len(occurrences):
        raise CurveRelationError(
            "terminal_mapping.segment_count does not match the terminal contour: "
            f"{segment_count} != {len(occurrences)}"
        )
    raw_mappings = terminal_mapping.get("mappings")
    if not isinstance(raw_mappings, Sequence) or isinstance(raw_mappings, (str, bytes)):
        raise CurveRelationError("terminal_mapping.mappings must be an array")

    output: List[CurveRelation] = []
    for mapping_ordinal, raw_mapping in enumerate(raw_mappings):
        if not isinstance(raw_mapping, Mapping):
            raise CurveRelationError("Each terminal mapping must be an object")
        copy_index = int(raw_mapping.get("copy_index", mapping_ordinal))
        mirror_sign = int(raw_mapping.get("mirror_sign", 0))
        if mirror_sign not in (-1, 1):
            raise CurveRelationError(
                f"Mapping {copy_index} has invalid mirror_sign {mirror_sign!r}"
            )
        raw_pairs = raw_mapping.get("segment_pairs")
        if not isinstance(raw_pairs, Sequence) or isinstance(raw_pairs, (str, bytes)):
            raise CurveRelationError(
                f"Mapping {copy_index} has no valid segment_pairs array"
            )
        for pair_index, raw_pair in enumerate(raw_pairs):
            if not isinstance(raw_pair, Mapping):
                raise CurveRelationError("Each segment pair must be an object")
            source_position = int(raw_pair["source_position"])
            target_position = int(raw_pair["target_position"])
            if not (0 <= source_position < len(occurrences)):
                raise CurveRelationError(
                    f"Invalid source_position {source_position} in mapping {copy_index}"
                )
            if not (0 <= target_position < len(occurrences)):
                raise CurveRelationError(
                    f"Invalid target_position {target_position} in mapping {copy_index}"
                )
            source = occurrences[source_position]
            target = occurrences[target_position]
            source_effective = _effective_orientation(
                source, int(raw_pair["source_orientation"])
            )
            target_effective = _effective_orientation(
                target, int(raw_pair["target_orientation"])
            )
            output.append(
                CurveRelation(
                    left_variable=source.variable,
                    right_variable=target.variable,
                    transform=CurveTransform(
                        reverse=(source_effective != target_effective),
                        mirror=(mirror_sign == -1),
                    ),
                    copy_index=copy_index,
                    pair_index=pair_index,
                    source_position=source_position,
                    target_position=target_position,
                )
            )
    return tuple(output)


def _subgroup(generators: Iterable[CurveTransform]) -> Tuple[CurveTransform, ...]:
    group = {IDENTITY}
    for generator in generators:
        group |= {item.compose(generator) for item in tuple(group)}
    changed = True
    while changed:
        changed = False
        for left in tuple(group):
            for right in tuple(group):
                product = left.compose(right)
                if product not in group:
                    group.add(product)
                    changed = True
    return tuple(sorted(group))


def _component_mode(symmetry_group: Sequence[CurveTransform]) -> str:
    group = set(symmetry_group)
    if MIRROR in group or (REVERSE in group and MIRROR_REVERSE in group):
        return "straight"
    if REVERSE in group:
        return "half_turn"
    if MIRROR_REVERSE in group:
        return "endpoint_swapping_reflection"
    return "free"


def _build_components(
    variables: Sequence[str],
    relations: Sequence[CurveRelation],
) -> Tuple[Tuple[CurveRelationComponent, ...], Dict[str, int]]:
    adjacency: Dict[str, List[Tuple[str, CurveTransform]]] = {
        variable: [] for variable in variables
    }
    for relation in relations:
        if relation.left_variable not in adjacency or relation.right_variable not in adjacency:
            raise CurveRelationError(
                "Terminal mapping references a curve variable absent from the formal profile"
            )
        adjacency[relation.right_variable].append(
            (relation.left_variable, relation.transform)
        )
        adjacency[relation.left_variable].append(
            (relation.right_variable, relation.transform)
        )

    components: List[CurveRelationComponent] = []
    component_by_variable: Dict[str, int] = {}
    visited: set[str] = set()
    for representative in variables:
        if representative in visited:
            continue
        transforms: Dict[str, CurveTransform] = {representative: IDENTITY}
        queue = [representative]
        cycle_generators: List[CurveTransform] = []
        visited.add(representative)
        while queue:
            current = queue.pop(0)
            current_transform = transforms[current]
            for neighbor, edge_transform in adjacency[current]:
                proposed = edge_transform.compose(current_transform)
                if neighbor not in transforms:
                    transforms[neighbor] = proposed
                    visited.add(neighbor)
                    queue.append(neighbor)
                else:
                    cycle_generators.append(
                        proposed.compose(transforms[neighbor])
                    )
        members = tuple(variable for variable in variables if variable in transforms)
        symmetry_group = _subgroup(cycle_generators)
        component = CurveRelationComponent(
            index=len(components),
            representative=representative,
            variables=members,
            transforms={name: transforms[name] for name in members},
            symmetry_group=symmetry_group,
            mode=_component_mode(symmetry_group),
        )
        components.append(component)
        for variable in members:
            component_by_variable[variable] = component.index
    return tuple(components), component_by_variable


def analyze_curve_relations(
    *,
    curve_variables: Sequence[str],
    occurrences: Sequence[object],
    terminal_mapping: Optional[Mapping[str, object]],
    enabled: bool = True,
) -> CurveRelationAnalysis:
    variables = tuple(str(variable) for variable in curve_variables)
    normalized_occurrences = tuple(
        _Occurrence(str(item.variable), bool(item.inverse)) for item in occurrences
    )
    if not enabled:
        components = tuple(
            CurveRelationComponent(
                index=index,
                representative=variable,
                variables=(variable,),
                transforms={variable: IDENTITY},
                symmetry_group=(IDENTITY,),
                mode="free",
            )
            for index, variable in enumerate(variables)
        )
        return CurveRelationAnalysis(
            enabled=False,
            components=components,
            component_by_variable={variable: index for index, variable in enumerate(variables)},
            relations=(),
        )
    relations = _parse_relations(normalized_occurrences, terminal_mapping)  # type: ignore[arg-type]
    components, component_by_variable = _build_components(variables, relations)
    return CurveRelationAnalysis(
        enabled=True,
        components=components,
        component_by_variable=component_by_variable,
        relations=relations,
    )
