#!/usr/bin/env python3
"""Exact template-sharing constraints induced by terminal contact mappings.

A formal curve variable is represented by one oriented polyline template.  A
terminal contact mapping pairs directed occurrences of these templates.  The
copy isometry may preserve or reverse orientation, so the paired templates are
related by one of the four elements of the Klein group generated by:

* ``reverse``: traverse the template backwards;
* ``mirror``: reflect the template in the plane.

This module builds connected components of curve variables under those exact
relations and parameterizes one representative template per component.  Cycle
relations automatically impose the appropriate self-symmetry:

* identity: unrestricted template;
* reverse: half-turn/central symmetry;
* mirror+reverse: reflection symmetry exchanging endpoints;
* mirror: a simple arc with fixed directed endpoints must be straight, so the
  artificial intermediate vertices are removed instead of being retained with
  zero turns.

The module is independent from the optimizer and from the formal classifier.
It only consumes an exported terminal contact mapping and produces a compact
parameterization plan.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple


SCHEMA_VERSION = "curve-template-duality-v1"


class TemplateConstraintError(ValueError):
    """Raised when exported terminal mapping data is missing or malformed."""


@dataclass(frozen=True, order=True)
class TemplateTransform:
    """A reverse/mirror transformation of one oriented curve template."""

    reverse: bool = False
    mirror: bool = False

    def compose(self, other: "TemplateTransform") -> "TemplateTransform":
        # Reverse and mirror commute on edge-length / signed-turn sequences.
        return TemplateTransform(
            reverse=self.reverse ^ other.reverse,
            mirror=self.mirror ^ other.mirror,
        )

    @property
    def turn_sign(self) -> int:
        # Reversal and reflection each negate signed turning.
        return -1 if self.reverse ^ self.mirror else 1

    @property
    def label(self) -> str:
        if self.reverse and self.mirror:
            return "mirror_reverse"
        if self.reverse:
            return "reverse"
        if self.mirror:
            return "mirror"
        return "identity"

    def apply(
        self,
        lengths: Sequence[float],
        turns: Sequence[float],
    ) -> Tuple[Tuple[float, ...], Tuple[float, ...]]:
        transformed_lengths = tuple(lengths)
        transformed_turns = tuple(turns)
        if self.reverse:
            transformed_lengths = tuple(reversed(transformed_lengths))
            transformed_turns = tuple(-value for value in reversed(transformed_turns))
        if self.mirror:
            transformed_turns = tuple(-value for value in transformed_turns)
        return transformed_lengths, transformed_turns


IDENTITY = TemplateTransform()
REVERSE = TemplateTransform(reverse=True)
MIRROR = TemplateTransform(mirror=True)
MIRROR_REVERSE = TemplateTransform(reverse=True, mirror=True)


@dataclass(frozen=True)
class TemplateRelation:
    left_variable: str
    right_variable: str
    transform: TemplateTransform
    copy_index: int
    pair_index: int
    source_position: int
    target_position: int

    def to_dict(self) -> Dict[str, object]:
        return {
            "left_variable": self.left_variable,
            "right_variable": self.right_variable,
            "transform": self.transform.label,
            "copy_index": self.copy_index,
            "pair_index": self.pair_index,
            "source_position": self.source_position,
            "target_position": self.target_position,
        }


@dataclass(frozen=True)
class TemplateComponent:
    index: int
    representative: str
    variables: Tuple[str, ...]
    transforms: Mapping[str, TemplateTransform]
    symmetry_group: Tuple[TemplateTransform, ...]
    mode: str
    requested_edge_count: int
    effective_edge_count: int
    free_length_count: int
    free_turn_count: int

    @property
    def forced_straight(self) -> bool:
        return self.mode == "straight"

    @property
    def representative_turn_forced_zero(self) -> bool:
        return self.effective_edge_count == 1 or self.mode in ("half_turn", "straight")

    def to_dict(self) -> Dict[str, object]:
        return {
            "component_index": self.index,
            "representative": self.representative,
            "variables": list(self.variables),
            "variable_transforms": {
                name: self.transforms[name].label for name in self.variables
            },
            "self_symmetry_group": [item.label for item in self.symmetry_group],
            "mode": self.mode,
            "requested_edge_count": self.requested_edge_count,
            "effective_edge_count": self.effective_edge_count,
            "requested_intermediate_points": self.requested_edge_count - 1,
            "effective_intermediate_points": self.effective_edge_count - 1,
            "free_length_parameter_count": self.free_length_count,
            "free_internal_turn_parameter_count": self.free_turn_count,
            "forced_straight": self.forced_straight,
        }


@dataclass(frozen=True)
class KappaReduction:
    parameter_names: Tuple[str, ...]
    assignments: Mapping[str, str]
    forced_zero_names: Tuple[str, ...]

    def to_dict(self) -> Dict[str, object]:
        return {
            "parameter_names": list(self.parameter_names),
            "assignments": dict(self.assignments),
            "forced_zero_names": list(self.forced_zero_names),
        }


@dataclass(frozen=True)
class TemplatePlan:
    enabled: bool
    requested_intermediate_points: int
    components: Tuple[TemplateComponent, ...]
    component_by_variable: Mapping[str, int]
    relations: Tuple[TemplateRelation, ...]
    kappa_reduction: KappaReduction

    def component_for(self, variable: str) -> TemplateComponent:
        return self.components[self.component_by_variable[variable]]

    @property
    def curve_parameter_count(self) -> int:
        return sum(
            component.free_length_count + component.free_turn_count
            for component in self.components
        )

    @property
    def kappa_parameter_names(self) -> Tuple[str, ...]:
        return self.kappa_reduction.parameter_names

    def to_dict(self) -> Dict[str, object]:
        return {
            "schema_version": SCHEMA_VERSION,
            "enabled": self.enabled,
            "requested_intermediate_points_per_variable": self.requested_intermediate_points,
            "component_count": len(self.components),
            "relation_count": len(self.relations),
            "forced_straight_variable_count": sum(
                len(component.variables)
                for component in self.components
                if component.forced_straight
            ),
            "components": [component.to_dict() for component in self.components],
            "relations": [relation.to_dict() for relation in self.relations],
            "kappa_reduction": self.kappa_reduction.to_dict(),
        }


@dataclass(frozen=True)
class DecodedTemplates:
    lengths: Mapping[str, Tuple[float, ...]]
    turns: Mapping[str, Tuple[float, ...]]
    kappa_parameter_values: Mapping[str, float]
    original_kappa_values: Mapping[str, float]
    consumed_value_count: int


@dataclass(frozen=True)
class _Occurrence:
    variable: str
    inverse: bool


class _SignedUnionFind:
    """Union-find for real variables with relations x = sign*y and x = 0."""

    def __init__(self, names: Iterable[str]) -> None:
        self.parent: Dict[str, str] = {}
        self.parity: Dict[str, int] = {}
        self.zero_roots: set[str] = set()
        for name in names:
            self.add(name)

    def add(self, name: str) -> None:
        if name not in self.parent:
            self.parent[name] = name
            self.parity[name] = 1

    def find(self, name: str) -> Tuple[str, int]:
        self.add(name)
        parent = self.parent[name]
        if parent == name:
            return name, 1
        root, parent_sign = self.find(parent)
        sign = self.parity[name] * parent_sign
        self.parent[name] = root
        self.parity[name] = sign
        return root, sign

    def mark_zero(self, name: str) -> None:
        root, _ = self.find(name)
        self.zero_roots.add(root)

    def union(self, left: str, right: str, sign: int) -> None:
        # Enforce left = sign * right.
        left_root, left_sign = self.find(left)
        right_root, right_sign = self.find(right)
        if left_root == right_root:
            if left_sign != sign * right_sign:
                self.zero_roots.add(left_root)
            return
        # left_sign*left_root = sign*right_sign*right_root
        # => left_root = left_sign*sign*right_sign * right_root
        root_sign = left_sign * sign * right_sign
        left_zero = left_root in self.zero_roots
        right_zero = right_root in self.zero_roots
        self.parent[left_root] = right_root
        self.parity[left_root] = root_sign
        self.zero_roots.discard(left_root)
        if left_zero or right_zero:
            self.zero_roots.add(right_root)

    def normalize_zero_roots(self) -> None:
        zeros = set()
        for root in tuple(self.zero_roots):
            normalized, _ = self.find(root)
            zeros.add(normalized)
        self.zero_roots = zeros



def _signed_name(expression: str) -> Tuple[int, Optional[str]]:
    expression = str(expression).strip()
    if expression == "0":
        return 0, None
    if expression.startswith("-"):
        return -1, expression[1:]
    return 1, expression


def _format_signed(sign: int, name: Optional[str]) -> str:
    if sign == 0 or name is None:
        return "0"
    return name if sign > 0 else f"-{name}"


def _effective_orientation(occurrence: _Occurrence, directed_orientation: int) -> int:
    if directed_orientation not in (-1, 1):
        raise TemplateConstraintError(
            f"Directed segment orientation must be +/-1, got {directed_orientation!r}"
        )
    literal_orientation = -1 if occurrence.inverse else 1
    return literal_orientation * directed_orientation


def _parse_relations(
    occurrences: Sequence[_Occurrence],
    terminal_mapping: Mapping[str, object],
) -> Tuple[TemplateRelation, ...]:
    if not isinstance(terminal_mapping, Mapping):
        raise TemplateConstraintError(
            "Missing terminal_mapping. Rerun the formal audit so the geometry "
            "solver can enforce copy-induced curve-template constraints."
        )
    segment_count = int(terminal_mapping.get("segment_count", -1))
    if segment_count != len(occurrences):
        raise TemplateConstraintError(
            "terminal_mapping.segment_count does not match the terminal contour: "
            f"{segment_count} != {len(occurrences)}"
        )
    raw_mappings = terminal_mapping.get("mappings")
    if not isinstance(raw_mappings, Sequence) or isinstance(raw_mappings, (str, bytes)):
        raise TemplateConstraintError("terminal_mapping.mappings must be an array")

    output: List[TemplateRelation] = []
    for mapping_ordinal, raw_mapping in enumerate(raw_mappings):
        if not isinstance(raw_mapping, Mapping):
            raise TemplateConstraintError("Each terminal mapping must be an object")
        copy_index = int(raw_mapping.get("copy_index", mapping_ordinal))
        mirror_sign = int(raw_mapping.get("mirror_sign", 0))
        if mirror_sign not in (-1, 1):
            raise TemplateConstraintError(
                f"Mapping {copy_index} has invalid mirror_sign {mirror_sign!r}"
            )
        raw_pairs = raw_mapping.get("segment_pairs")
        if not isinstance(raw_pairs, Sequence) or isinstance(raw_pairs, (str, bytes)):
            raise TemplateConstraintError(
                f"Mapping {copy_index} has no valid segment_pairs array"
            )
        for pair_index, raw_pair in enumerate(raw_pairs):
            if not isinstance(raw_pair, Mapping):
                raise TemplateConstraintError("Each segment pair must be an object")
            source_position = int(raw_pair["source_position"])
            target_position = int(raw_pair["target_position"])
            if not (0 <= source_position < len(occurrences)):
                raise TemplateConstraintError(
                    f"Invalid source_position {source_position} in mapping {copy_index}"
                )
            if not (0 <= target_position < len(occurrences)):
                raise TemplateConstraintError(
                    f"Invalid target_position {target_position} in mapping {copy_index}"
                )
            source_orientation = int(raw_pair["source_orientation"])
            target_orientation = int(raw_pair["target_orientation"])
            source_occurrence = occurrences[source_position]
            target_occurrence = occurrences[target_position]
            source_effective = _effective_orientation(
                source_occurrence, source_orientation
            )
            target_effective = _effective_orientation(
                target_occurrence, target_orientation
            )
            transform = TemplateTransform(
                reverse=(source_effective != target_effective),
                mirror=(mirror_sign == -1),
            )
            # The equality is:
            #   template(source variable) = transform(template(target variable)).
            output.append(
                TemplateRelation(
                    left_variable=source_occurrence.variable,
                    right_variable=target_occurrence.variable,
                    transform=transform,
                    copy_index=copy_index,
                    pair_index=pair_index,
                    source_position=source_position,
                    target_position=target_position,
                )
            )
    return tuple(output)


def _subgroup(generators: Iterable[TemplateTransform]) -> Tuple[TemplateTransform, ...]:
    group = {IDENTITY}
    for generator in generators:
        group |= {item.compose(generator) for item in tuple(group)}
    # Close once more in case independent generators were added successively.
    changed = True
    while changed:
        changed = False
        for left in tuple(group):
            for right in tuple(group):
                product = left.compose(right)
                if product not in group:
                    group.add(product)
                    changed = True
    return tuple(sorted(group))


def _component_mode(symmetry_group: Sequence[TemplateTransform]) -> str:
    group = set(symmetry_group)
    if MIRROR in group:
        return "straight"
    if REVERSE in group and MIRROR_REVERSE in group:
        # Their product is MIRROR; retained for defensive clarity.
        return "straight"
    if REVERSE in group:
        return "half_turn"
    if MIRROR_REVERSE in group:
        return "endpoint_swapping_reflection"
    return "free"


def _free_counts(mode: str, edge_count: int) -> Tuple[int, int]:
    if edge_count <= 0:
        raise TemplateConstraintError("edge_count must be positive")
    if mode == "straight":
        return 1, 0
    if mode == "free":
        return edge_count, max(0, edge_count - 2)

    free_lengths = (edge_count + 1) // 2
    turn_count = edge_count - 1
    if mode == "half_turn":
        return free_lengths, turn_count // 2
    if mode == "endpoint_swapping_reflection":
        if turn_count == 0:
            return free_lengths, 0
        if turn_count % 2 == 1:
            # Paired turns plus one derived central turn.
            return free_lengths, turn_count // 2
        # All turns occur in equal pairs; derive the final pair from Kappa.
        return free_lengths, max(0, turn_count // 2 - 1)
    raise TemplateConstraintError(f"Unknown component mode {mode!r}")


def _build_components(
    variables: Sequence[str],
    relations: Sequence[TemplateRelation],
    requested_edge_count: int,
) -> Tuple[Tuple[TemplateComponent, ...], Dict[str, int]]:
    adjacency: Dict[str, List[Tuple[str, TemplateTransform]]] = {
        variable: [] for variable in variables
    }
    for relation in relations:
        if relation.left_variable not in adjacency or relation.right_variable not in adjacency:
            raise TemplateConstraintError(
                "Terminal mapping references a curve variable absent from the formal profile"
            )
        adjacency[relation.right_variable].append(
            (relation.left_variable, relation.transform)
        )
        adjacency[relation.left_variable].append(
            (relation.right_variable, relation.transform)
        )

    components: List[TemplateComponent] = []
    component_by_variable: Dict[str, int] = {}
    visited: set[str] = set()
    for representative in variables:
        if representative in visited:
            continue
        transforms: Dict[str, TemplateTransform] = {representative: IDENTITY}
        queue = [representative]
        cycle_generators: List[TemplateTransform] = []
        visited.add(representative)
        while queue:
            current = queue.pop(0)
            current_transform = transforms[current]
            for neighbor, edge_transform in adjacency[current]:
                proposed = edge_transform.compose(current_transform)
                if neighbor not in transforms:
                    transforms[neighbor] = proposed
                    visited.add(neighbor)
                    queue.append(neighbor)
                else:
                    cycle_generators.append(
                        proposed.compose(transforms[neighbor])
                    )
        variable_names = tuple(
            variable for variable in variables if variable in transforms
        )
        symmetry_group = _subgroup(cycle_generators)
        mode = _component_mode(symmetry_group)
        effective_edge_count = 1 if mode == "straight" else requested_edge_count
        free_lengths, free_turns = _free_counts(mode, effective_edge_count)
        index = len(components)
        component = TemplateComponent(
            index=index,
            representative=representative,
            variables=variable_names,
            transforms={name: transforms[name] for name in variable_names},
            symmetry_group=symmetry_group,
            mode=mode,
            requested_edge_count=requested_edge_count,
            effective_edge_count=effective_edge_count,
            free_length_count=free_lengths,
            free_turn_count=free_turns,
        )
        components.append(component)
        for variable in variable_names:
            component_by_variable[variable] = index
    return tuple(components), component_by_variable


def _add_expression_equality(
    union_find: _SignedUnionFind,
    left_expression: str,
    right_expression: str,
) -> None:
    left_sign, left_name = _signed_name(left_expression)
    right_sign, right_name = _signed_name(right_expression)
    if left_sign == 0 and right_sign == 0:
        return
    if left_sign == 0 and right_name is not None:
        union_find.mark_zero(right_name)
        return
    if right_sign == 0 and left_name is not None:
        union_find.mark_zero(left_name)
        return
    assert left_name is not None and right_name is not None
    union_find.union(left_name, right_name, left_sign * right_sign)


def _negate_expression(expression: str) -> str:
    sign, name = _signed_name(expression)
    return _format_signed(-sign, name)


def _reduce_kappas(
    components: Sequence[TemplateComponent],
    kappa_assignments: Mapping[str, str],
) -> KappaReduction:
    original_names = sorted(
        {
            name
            for expression in kappa_assignments.values()
            for sign, name in [_signed_name(str(expression))]
            if sign != 0 and name is not None
        }
    )
    union_find = _SignedUnionFind(original_names)

    for component in components:
        representative_variable = component.representative
        representative_expression = str(kappa_assignments[representative_variable])
        for variable in component.variables:
            expression = str(kappa_assignments[variable])
            transform = component.transforms[variable]
            expected = (
                representative_expression
                if transform.turn_sign > 0
                else _negate_expression(representative_expression)
            )
            _add_expression_equality(union_find, expression, expected)
        if component.representative_turn_forced_zero:
            sign, name = _signed_name(representative_expression)
            if sign != 0 and name is not None:
                union_find.mark_zero(name)

    union_find.normalize_zero_roots()
    roots_to_members: Dict[str, List[Tuple[str, int]]] = {}
    for name in original_names:
        root, sign = union_find.find(name)
        roots_to_members.setdefault(root, []).append((name, sign))

    canonical_root_name: Dict[str, str] = {}
    for root, members in roots_to_members.items():
        canonical_root_name[root] = min(name for name, _ in members)

    assignments: Dict[str, str] = {}
    forced_zero_names: List[str] = []
    parameter_roots: List[str] = []
    for root in sorted(roots_to_members, key=lambda item: canonical_root_name[item]):
        if root in union_find.zero_roots:
            forced_zero_names.extend(name for name, _ in roots_to_members[root])
        else:
            parameter_roots.append(root)
    parameter_names = tuple(canonical_root_name[root] for root in parameter_roots)

    for name in original_names:
        root, sign_to_root = union_find.find(name)
        if root in union_find.zero_roots:
            assignments[name] = "0"
            continue
        canonical = canonical_root_name[root]
        canonical_root, canonical_sign = union_find.find(canonical)
        assert canonical_root == root
        # name = sign_to_root*root and canonical = canonical_sign*root.
        sign_to_canonical = sign_to_root * canonical_sign
        assignments[name] = _format_signed(sign_to_canonical, canonical)

    return KappaReduction(
        parameter_names=parameter_names,
        assignments=assignments,
        forced_zero_names=tuple(sorted(set(forced_zero_names))),
    )


def build_plan(
    *,
    curve_variables: Sequence[str],
    occurrences: Sequence[object],
    terminal_mapping: Optional[Mapping[str, object]],
    kappa_assignments: Mapping[str, str],
    intermediate_points: int,
    enabled: bool = True,
) -> TemplatePlan:
    if intermediate_points < 0:
        raise TemplateConstraintError("intermediate_points must be nonnegative")
    variables = tuple(str(variable) for variable in curve_variables)
    if not variables:
        raise TemplateConstraintError("A geometric profile must contain curve variables")
    parsed_occurrences = tuple(
        _Occurrence(
            variable=str(getattr(occurrence, "variable")),
            inverse=bool(getattr(occurrence, "inverse")),
        )
        for occurrence in occurrences
    )
    requested_edge_count = intermediate_points + 1
    relations: Tuple[TemplateRelation, ...]
    if enabled:
        relations = _parse_relations(parsed_occurrences, terminal_mapping or {})
    else:
        relations = ()
    components, component_by_variable = _build_components(
        variables,
        relations,
        requested_edge_count,
    )
    kappa_reduction = _reduce_kappas(components, kappa_assignments)
    return TemplatePlan(
        enabled=enabled,
        requested_intermediate_points=intermediate_points,
        components=components,
        component_by_variable=component_by_variable,
        relations=relations,
        kappa_reduction=kappa_reduction,
    )


def _expand_palindrome(values: Sequence[float], total_count: int) -> Tuple[float, ...]:
    output = [0.0] * total_count
    for index, value in enumerate(values):
        output[index] = float(value)
        output[total_count - 1 - index] = float(value)
    return tuple(output)


def _representative_lengths(
    component: TemplateComponent,
    free_values: Sequence[float],
) -> Tuple[float, ...]:
    if component.mode in ("free", "straight"):
        return tuple(float(value) for value in free_values)
    return _expand_palindrome(free_values, component.effective_edge_count)


def _representative_turns(
    component: TemplateComponent,
    free_values: Sequence[float],
    representative_kappa: float,
) -> Tuple[float, ...]:
    turn_count = component.effective_edge_count - 1
    if turn_count == 0:
        return ()
    free_values = tuple(float(value) for value in free_values)
    if component.mode == "free":
        return free_values + (representative_kappa - sum(free_values),)
    if component.mode == "half_turn":
        output = [0.0] * turn_count
        for index, value in enumerate(free_values):
            output[index] = value
            output[turn_count - 1 - index] = -value
        # A central turn, when present, remains exactly zero.
        return tuple(output)
    if component.mode == "endpoint_swapping_reflection":
        output = [0.0] * turn_count
        pair_count = turn_count // 2
        if turn_count % 2 == 1:
            for index, value in enumerate(free_values):
                output[index] = value
                output[turn_count - 1 - index] = value
            output[pair_count] = representative_kappa - 2.0 * sum(free_values)
            return tuple(output)
        values = list(free_values)
        derived = representative_kappa / 2.0 - sum(values)
        values.append(derived)
        for index, value in enumerate(values):
            output[index] = value
            output[turn_count - 1 - index] = value
        return tuple(output)
    if component.mode == "straight":
        return ()
    raise TemplateConstraintError(f"Unknown component mode {component.mode!r}")


def _expression_value(expression: str, values: Mapping[str, float]) -> float:
    sign, name = _signed_name(expression)
    if sign == 0 or name is None:
        return 0.0
    return sign * float(values[name])


def decode_templates(
    plan: TemplatePlan,
    kappa_assignments: Mapping[str, str],
    values: Sequence[float],
    *,
    start: int = 0,
    kappa_values: Optional[Mapping[str, float]] = None,
) -> DecodedTemplates:
    """Decode component shape values.

    When ``kappa_values`` is omitted, reduced Kappa parameters are read after
    all component length/turn parameters.  Geometry code normally reads angle
    parameters between those two blocks and therefore passes ``kappa_values``
    explicitly after decoding them.
    """
    cursor = start
    raw_components: List[Tuple[TemplateComponent, Tuple[float, ...], Tuple[float, ...]]] = []
    for component in plan.components:
        free_lengths = tuple(
            float(values[cursor + offset])
            for offset in range(component.free_length_count)
        )
        cursor += component.free_length_count
        free_turns = tuple(
            float(values[cursor + offset])
            for offset in range(component.free_turn_count)
        )
        cursor += component.free_turn_count
        raw_components.append((component, free_lengths, free_turns))

    if kappa_values is None:
        reduced_values = {
            name: float(values[cursor + index])
            for index, name in enumerate(plan.kappa_parameter_names)
        }
        cursor += len(plan.kappa_parameter_names)
    else:
        reduced_values = {
            name: float(kappa_values[name]) for name in plan.kappa_parameter_names
        }

    original_kappa_values = {
        original: _expression_value(expression, reduced_values)
        for original, expression in plan.kappa_reduction.assignments.items()
    }

    lengths: Dict[str, Tuple[float, ...]] = {}
    turns: Dict[str, Tuple[float, ...]] = {}
    for component, free_lengths, free_turns in raw_components:
        representative_expression = str(kappa_assignments[component.representative])
        sign, name = _signed_name(representative_expression)
        if sign == 0 or name is None:
            representative_kappa = 0.0
        else:
            representative_kappa = sign * original_kappa_values[name]
        representative_lengths = _representative_lengths(component, free_lengths)
        representative_turns = _representative_turns(
            component, free_turns, representative_kappa
        )
        for variable in component.variables:
            variable_lengths, variable_turns = component.transforms[variable].apply(
                representative_lengths, representative_turns
            )
            lengths[variable] = variable_lengths
            turns[variable] = variable_turns

    return DecodedTemplates(
        lengths=lengths,
        turns=turns,
        kappa_parameter_values=reduced_values,
        original_kappa_values=original_kappa_values,
        consumed_value_count=cursor - start,
    )


def max_relation_error(
    plan: TemplatePlan,
    lengths: Mapping[str, Sequence[float]],
    turns: Mapping[str, Sequence[float]],
) -> float:
    """Return the largest per-coordinate violation of the terminal relations."""
    maximum = 0.0
    for relation in plan.relations:
        expected_lengths, expected_turns = relation.transform.apply(
            lengths[relation.right_variable],
            turns[relation.right_variable],
        )
        actual_lengths = tuple(lengths[relation.left_variable])
        actual_turns = tuple(turns[relation.left_variable])
        if len(expected_lengths) != len(actual_lengths):
            return float("inf")
        if len(expected_turns) != len(actual_turns):
            return float("inf")
        maximum = max(
            maximum,
            *(abs(left - right) for left, right in zip(actual_lengths, expected_lengths)),
            *(abs(left - right) for left, right in zip(actual_turns, expected_turns)),
        )
    return maximum
