"""Machine-readable status of every analysis stage."""
from __future__ import annotations
from typing import Dict
import settings

def method_registry() -> Dict[str, Dict[str, object]]:
    return {
        "placement_enumerator": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": True, "description": "Finite exhaustive enumeration of pole-image placements and contact-imposed parities."},
        "positive_word_length_filter": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": True, "description": "Rejects a generated two-equation system when equality of word lengths has no solution with every formal variable assigned a strictly positive integer length."},
        "formal_word_solver": {"status": settings.STATUS_SOUND_INCOMPLETE, "automatic_rejection_allowed": True, "description": "Default exact-partial mode labels a case exact only after its complete residual graph is built. Finite and fixed-context power SCCs are compiled into complete finite/nested-power families; complete but morphic graphs and graph-budget truncations are retained without downstream profiles. Legacy bounded mode remains optional."},
        "family_representative_expansion": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": False, "description": "Independent optional adapter for explicit minimum, fixed, or bounded-range exponent specialization. It is disabled by default; exact parametric families remain separate from primitive finite solutions."},
        "curve_term_solver": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": False, "description": "Post-word-solver formal interpretation of terminal mappings. It emits explicit Straight(lambda), Mirror and Inverse curve terms and positive straight-length classes without modifying the generic word-equation solver."},
        "formal_cycle_unroll_cap": {"status": settings.STATUS_BOUNDED, "automatic_rejection_allowed": False, "description": "Independent anti-echo policy. It prunes a branch after repeated returns to the same residual system, reports every hit as truncation, and does not recognize parametric families."},
        "decorated_solution_canonicalization": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": False, "description": "Canonical key for the terminal contour together with both copy mappings, modulo pole exchange, curve/angle renaming, copy permutation, and global mirror. It annotates but does not delete profiles."},
        "point_angle_solver": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": True, "description": "Exact signed angle classes and forced-zero point turns."},
        "total_turn_filter": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": True, "description": "Exact necessary total-turn feasibility test in the symbolic model."},
        "pole_angle_filter": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": True, "description": "Exact necessary simultaneous inequalities at P0 and P1. Retained as a cheap early filter; the authoritative downstream check combines both poles with inner and outer rotation equations."},
        "joint_angle_feasibility": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": True, "description": "One exact rational linear program jointly enforces the inner and outer total turns, every angle-class bound, and both strict pole margins. A profile survives only when a strictly positive rational margin exists."},
        "translation_holonomy_filter": {"status": settings.STATUS_SOUND_INCOMPLETE, "automatic_rejection_allowed": True, "description": "Rejects only formally proved chord-closure contradictions; undecided systems are retained."},
        "forced_point_coincidence": {"status": settings.STATUS_SOUND_INCOMPLETE, "automatic_rejection_allowed": True, "description": "Integrated exact symbolic prefix-identity filter on the inner and outer boundaries. It rejects only forced unintended coincidences and remains incomplete for identities requiring nonlinear trigonometric consequences."},
        "external_boundary_builder": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": False, "description": "Constructs the shared inner/outer boundary system, exact linear turn equations, and chord expressions used by independent downstream filters."},
        "placed_copy_geometry": {"status": settings.STATUS_SOUND_INCOMPLETE, "automatic_rejection_allowed": True, "description": "Places the reference tile and both copies in one symbolic frame using one global direct or reflected isometry per copy. It rejects forced self-coincidences and exact same-side arc overlaps; isolated extra cross-copy point contacts and generic curved crossings are deliberately not rejected."},
        "curve_template_duality": {"status": settings.STATUS_EXACT, "automatic_rejection_allowed": False, "description": "Numeric compiler and validator for the formal curve-term solution. It propagates full edge-length and internal-turn templates under reversal/reflection and removes artificial vertices from Straight(lambda) values."},
        "geometric_candidate_search": {"status": settings.STATUS_HEURISTIC, "automatic_rejection_allowed": False, "description": "Differential evolution searches the reduced polygonal template model. Found contours satisfy local terminal curve-template duality and prototype simplicity, but full three-copy non-overlap is still not certified; failures remain inconclusive."},
        "joint_translation_z3": {"status": settings.STATUS_SOUND_INCOMPLETE, "automatic_rejection_allowed": True, "description": "Z3/NLSAT solves a polynomial relaxation augmented with pointwise equations from one global direct or reflected isometry for each copy. UNSAT is a safe rejection for the encoded model; SAT is only a candidate because generic curved-arc intersections, winding intervals, and complete three-interior disjointness are not encoded."},
    }
